export const genres = [
  { name: "Action", animeId: 1, mangaId: 1 },
  { name: "Adventure", animeId: 2, mangaId: 2 },
  { name: "Avant Garde", animeId: 5, mangaId: 5 },
  { name: "Award Winning", animeId: 46, mangaId: 46 },
  { name: "Boys Love", animeId: 28, mangaId: 28 },
  { name: "Comedy", animeId: 4, mangaId: 4 },
  { name: "Drama", animeId: 8, mangaId: 8 },
  { name: "Fantasy", animeId: 10, mangaId: 10 },
  { name: "Girls Love", animeId: 26, mangaId: 26 },
  { name: "Gourmet", animeId: 47, mangaId: 47 },
  { name: "Horror", animeId: 14, mangaId: 14 },
  { name: "Mystery", animeId: 7, mangaId: 7 },
  { name: "Romance", animeId: 22, mangaId: 22 },
  { name: "Sci-Fi", animeId: 24, mangaId: 24 },
  { name: "Slice of Life", animeId: 36, mangaId: 36 },
  { name: "Sports", animeId: 30, mangaId: 30 },
  { name: "Supernatural", animeId: 37, mangaId: 37 },
  { name: "Suspense", animeId: 41, mangaId: 45 },
  { name: "Ecchi", animeId: 9, mangaId: 9 },
  { name: "Erotica", animeId: 49, mangaId: 49 },
  { name: "Hentai", animeId: 12, mangaId: 12 },
  { name: "Adult Cast", animeId: 50, mangaId: 50 },
  { name: "Anthropomorphic", animeId: 51, mangaId: 51 },
  { name: "CGDCT", animeId: 52, mangaId: 52 },
  { name: "Childcare", animeId: 53, mangaId: 53 },
  { name: "Combat Sports", animeId: 54, mangaId: 54 },
  { name: "Crossdressing", animeId: 81, mangaId: 44 },
  { name: "Delinquents", animeId: 55, mangaId: 55 },
  { name: "Detective", animeId: 39, mangaId: 39 },
  { name: "Educational", animeId: 56, mangaId: 56 },
  { name: "Gag Humor", animeId: 57, mangaId: 57 },
  { name: "Gore", animeId: 58, mangaId: 58 },
  { name: "Harem", animeId: 35, mangaId: 35 },
  { name: "High Stakes Game", animeId: 59, mangaId: 59 },
  { name: "Historical", animeId: 13, mangaId: 13 },
  { name: "Idols (Female)", animeId: 60, mangaId: 60 },
  { name: "Idols (Male)", animeId: 61, mangaId: 61 },
  { name: "Isekai", animeId: 62, mangaId: 62 },
  { name: "Iyashikei", animeId: 63, mangaId: 63 },
  { name: "Love Polygon", animeId: 64, mangaId: 64 },
  { name: "Love Status Quo", animeId: 74, mangaId: 75 },
  { name: "Magical Sex Shift", animeId: 65, mangaId: 65 },
  { name: "Mahou Shoujo", animeId: 66, mangaId: 66 },
  { name: "Martial Arts", animeId: 17, mangaId: 17 },
  { name: "Mecha", animeId: 18, mangaId: 18 },
  { name: "Medical", animeId: 67, mangaId: 67 },
  { name: "Memoir", animeId: null, mangaId: 68 },
  { name: "Military", animeId: 38, mangaId: 38 },
  { name: "Music", animeId: 19, mangaId: 19 },
  { name: "Mythology", animeId: 6, mangaId: 6 },
  { name: "Organized Crime", animeId: 68, mangaId: 69 },
  { name: "Otaku Culture", animeId: 69, mangaId: 70 },
  { name: "Parody", animeId: 20, mangaId: 20 },
  { name: "Performing Arts", animeId: 70, mangaId: 71 },
  { name: "Pets", animeId: 71, mangaId: 72 },
  { name: "Psychological", animeId: 40, mangaId: 40 },
  { name: "Racing", animeId: 3, mangaId: 3 },
  { name: "Reincarnation", animeId: 72, mangaId: 73 },
  { name: "Reverse Harem", animeId: 73, mangaId: 74 },
  { name: "Samurai", animeId: 21, mangaId: 21 },
  { name: "School", animeId: 23, mangaId: 23 },
  { name: "Showbiz", animeId: 75, mangaId: 76 },
  { name: "Space", animeId: 29, mangaId: 29 },
  { name: "Strategy Game", animeId: 11, mangaId: 11 },
  { name: "Super Power", animeId: 31, mangaId: 31 },
  { name: "Survival", animeId: 76, mangaId: 77 },
  { name: "Team Sports", animeId: 77, mangaId: 78 },
  { name: "Time Travel", animeId: 78, mangaId: 79 },
  { name: "Urban Fantasy", animeId: 82, mangaId: 83 },
  { name: "Vampire", animeId: 32, mangaId: 32 },
  { name: "Video Game", animeId: 79, mangaId: 80 },
  { name: "Villainess", animeId: 83, mangaId: 81 },
  { name: "Visual Arts", animeId: 80, mangaId: 82 },
  { name: "Workplace", animeId: 48, mangaId: 48 },
  { name: "Josei", animeId: 43, mangaId: 42 },
  { name: "Kids", animeId: 15, mangaId: 15 },
  { name: "Seinen", animeId: 42, mangaId: 41 },
  { name: "Shoujo", animeId: 25, mangaId: 25 },
  { name: "Shounen", animeId: 27, mangaId: 27 },
];